const express = require('express');
const authGuard = require('../../middlewares/auth');
const sendResponse = require('../../middlewares/sendResponse');
const optionalAuth = require('../../middlewares/optionalAuth');

const answerRoutes = require('./answer/answer.route');
const gamificationRoutes = require('./gamification/gamification.route');
const studentRoutes = require('./student/student.route');
const testseriesRoutes = require('./testseries/testseries.route');
const postRoutes = require('./post/post.route');
const searchRoutes = require('./search/search.route');
const newHomepage = require('./homepage/homepage.route');
const dynamicFeedRoutes = require('./dynamicfeed/feed.route');
const mathJaxRoute = require('./mathjax/mathjax.route');
const formulasRoute = require('./formulas/formulas.route');
const iconsRoute = require('./icons/icons.route');
const configRoute = require('./config/config.route');
const groupChatRoute = require('./groupchat/groupchat.route');
const dashboardRoutes = require('./dashboard/dashboard.route');
const feedbackRoutes = require('./feedback/feedback.route');
const unbanRoutes = require('./unban/unban.route');
const dnShortsRoutes = require('./dnShorts/dnShorts.route');
const ticketsRoutes = require('./paneltickets/paneltickets.route');

// const userRoutes = require('./server/user/user.route');
// const authRoutes = require('./server/auth/auth.route');
// const timetableRoutes =require('./timetable/timetable.route')
const deeplinkRoute = require('./numbersdeeplink/numbersdeeplink.route');
const deeplinkRoute2 = require('./deeplink/deeplink.route');
const brainlyRoute = require('./brainly/brainly.route');
const cameraRoutes = require('./camera/camera.route');
const examCornerRoutes = require('./exam_corner/examcorner.route');
const timetableRoutes = require('./timetable/timetable.route');
const crawlerRoutes = require('./crawler/crawler.route');
const sharingRoutes = require('./sharing/sharing.route');
const questionRoutes = require('./question/question.route');
// const optInRoutes = require('./optin/optIn.route');
const optInRoutes = require('./whatsApp/optIn.route');
const structuredCourseRoutes = require('./structuredcourse/structuredcourse.route');
const paymentRoutes = require('./payment/payment.route');
const walletRoutes = require('./wallet/wallet.route');
const packageRoutes = require('./package/package.route');
const bountyRoutes = require('./bounty/bounty.route');
const alfredRoutes = require('./alfred/alfred.route');
const courseRoutes = require('./course/course.route');
const teslaRoutes = require('./tesla/tesla.route');
const liveclassRoutes = require('./liveclass/liveclass.route');
const gamesRoutes = require('./games/games.route');
const assignmentRoutes = require('./assignment/assignment.route');
const personalizeRoutes = require('./personalization/personalization.route');
const preporcessServiceRoutes = require('./preprocess/preprocess.route');
const banRoute = require('./ban/ban.route');
const socialStudentRoutes = require('./socialstudent/socialstudent.route');
const liveclassPanelRoutes = require('./liveclass_panel/liveclass_panel.route');
const nudgeRoutes = require('./nudge/nudge.route');
// coupon routes
const couponRoutes = require('./coupon/coupon.route');
// JEE Packages Route
const importPackageRoutes = require('./importPackage/importPackage.route');
// trail routes
const trailRoutes = require('./trail/trail.route');
const testSimulationRoute = require('./test_simulation/test_simulation.route');
const questionPuchoContestRoute = require('./question_pucho_contest/question_pucho_contest.route');

const dexterRoutes = require('./dexter/dexter.route');
const rewardsRoutes = require('./rewards/rewards.route');
const quizRoute = require('./quiz_notifications/quiz_notifications.route');
const studyDostRoute = require('./studydost/studydost.route');
const vodScheduleRoute = require('./vod_schedule/vod_schedule.route');
const adsRoute = require('./ads/ads.route');
const matchPageRoute = require('./matchpage/matchpage.route');
const faqRoute = require('./faq/faq.route');
const scholarshipRoute = require('./scholarship/scholarship.route');
const doubtPeCharcha = require('./doubtPeCharcha/doubtPeCharcha.route');
const studyGroupRoutes = require('./studyGroup/studyGroup.route');
const recommendationRoutes = require('./recommendation/recommendation.route');
const storiesRoutes = require('./stories/stories.route');
const districtRoutes = require('./district/district.route');
const quizRoutes = require('./quiz/quiz.route');
const quiztfsRoutes = require('./quiztfs/quiztfsroute');
const practiceCornerRoutes = require('./practice_corner/practiceCorner.route');
const landingRoutes = require('./landing/landing.route');
const paidUserChamionshipRoutes = require('./paid_user_championship/paidUserChampionship.route');
const commonRoutes = require('./common/common.routes');
const webBannerRoutes = require('./web_banner/web_banner.route');
const sevenPmQuizRoute = require('./seven_pm_quiz/seven_pm_quiz.route');
const teacherRoutes = require('./teacher/teacher.route');
const twentyFourSevenQuizRoutes = require('./twenty_four_seven_quiz_contest/twenty_four_seven_quiz_contest.route');
const studyTimerRoutes = require('./studyTimer/studyTimer.route');
const practiceEnglishRoutes = require('./practiceEnglish/practiceEnglish.route');
const olympiadRoutes = require('./olympiad/olympiad.route');
const clpRoutes = require('./clp/clp.route');

const audioToolTipRoute = require('./audio_tooltip/audiotooltip.route');
const nkcRoute = require('./nkcweb/nkc.route');
const doubtSuggesterRoutes = require('./doubtSuggester/doubtSuggester.route');
const webLandingRoute = require('./web_landing/weblanding.route');
const dnExamRewardsRoutes = require('./dn_exam_rewards/dn_exam_rewards.route');
const webLibrary = require('./web_library/web_library.route');
const resultpage = require('./resultPage/result.route');
const contactsRoutes = require('./contacts/contacts.route');

// const submitAddressCtrl = require('./submit-address/submit-address.controller');

const router = express.Router(); // eslint-disable-line new-cap

/** GET /health-check - Check service health */
router.get('/health-check', (req, res) => res.send('OK2'));
router.use('/district', districtRoutes);
router.use('/stories', storiesRoutes);
router.use('/answers', answerRoutes);
router.use('/gamification', gamificationRoutes);
router.use('/deeplink', deeplinkRoute2);
router.use('/formulas', formulasRoute);
router.use('/student', studentRoutes);
router.use('/testseries', testseriesRoutes);
router.use('/post', authGuard, postRoutes);
router.use('/timetable', authGuard, timetableRoutes);
router.use('/nfeed', dynamicFeedRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/search', authGuard, searchRoutes);
router.use('/crawler', crawlerRoutes);
router.use('/feedback', authGuard, feedbackRoutes);
router.use('/mathjax', mathJaxRoute);
router.use('/homepage', newHomepage);
router.use('/groupchat', groupChatRoute);
router.use('/numbersdeeplink', deeplinkRoute);
router.use('/brainly', brainlyRoute);
router.use('/icons', iconsRoute, sendResponse);
router.use('/config', configRoute);
router.use('/sharing', sharingRoutes);
router.use('/question', questionRoutes);
router.use('/whatsapp', optInRoutes);
router.use('/structured-course', structuredCourseRoutes);
router.use('/payment', paymentRoutes);
router.use('/wallet', walletRoutes);
router.use('/package', packageRoutes);
router.use('/camera', cameraRoutes);
router.use('/bounty', bountyRoutes, sendResponse);
router.use('/course', courseRoutes, sendResponse);
router.use('/tesla', teslaRoutes, sendResponse);
router.use('/alfred', alfredRoutes, sendResponse);
router.use('/liveclass', liveclassRoutes);
router.use('/games', gamesRoutes);
router.use('/tesla', teslaRoutes, sendResponse);
router.use('/alfred', alfredRoutes, sendResponse);
router.use('/assignment', assignmentRoutes);
router.use('/personalize', personalizeRoutes);
router.use('/preprocess', preporcessServiceRoutes);
router.use('/ban', banRoute);
router.use('/social', socialStudentRoutes);
router.use('/liveclasspanel', liveclassPanelRoutes);
router.use('/nudge', nudgeRoutes, sendResponse);
router.use('/coupon', couponRoutes);
router.use('/trail', trailRoutes);
router.use('/importPackage', importPackageRoutes);
router.use('/quiz', quizRoute);
router.use('/vod', vodScheduleRoute);
router.use('/ads', adsRoute);
router.use('/dexter', dexterRoutes);
router.use('/rewards', rewardsRoutes);
router.use('/studydost', studyDostRoute);
router.use('/matchpage', matchPageRoute);
router.use('/faq', faqRoute);
router.use('/scholarship', scholarshipRoute);
router.use('/p2p', doubtPeCharcha);
router.use('/unban', unbanRoutes);
router.use('/study-group', studyGroupRoutes);
router.use('/recommendation', optionalAuth, recommendationRoutes);
router.use('/exam-corner', authGuard, examCornerRoutes, sendResponse);
router.use('/quiz', quizRoutes);
router.use('/quiztfs', quiztfsRoutes);
router.use('/practice-corner', practiceCornerRoutes);
router.use('/landing', landingRoutes);
router.use('/paid-user-championship', authGuard, paidUserChamionshipRoutes, sendResponse);
router.use('/common', authGuard, commonRoutes, sendResponse);
router.use('/question-pucho-contest', questionPuchoContestRoute, sendResponse);
router.use('/web-banner', webBannerRoutes, sendResponse);
router.use('/seven-pm-quiz', sevenPmQuizRoute, sendResponse);
router.use('/teacher', teacherRoutes);
router.use('/twenty-four-seven-quiz-contest', twentyFourSevenQuizRoutes, sendResponse);
router.use('/study-timer', studyTimerRoutes);
router.use('/practice-english', practiceEnglishRoutes);
router.use('/olympiad', olympiadRoutes, sendResponse);
router.use('/audio-tooltip', audioToolTipRoute, sendResponse);
router.use('/dn-shorts', dnShortsRoutes);
router.use('/tickets', ticketsRoutes);
router.use('/clp', clpRoutes, sendResponse);
router.use('/nkc', nkcRoute);
router.use('/doubt-suggester', doubtSuggesterRoutes);
router.use('/web-landing', webLandingRoute);
router.use('/dn-exam-rewards', dnExamRewardsRoutes);
router.use('/web_library', webLibrary, sendResponse);
router.use('/result', resultpage);
router.use('/contacts', contactsRoutes);
// router.use('/submit-address', authGuard, submitAddressCtrl, sendResponse);
// router.route('/submit-address').post(authGuard, submitAddressCtrl.submitAddress, sendResponse);

if (process.env.TEST_SIMULATION === 'true') {
    router.use('/test-simulation', testSimulationRoute);
}
module.exports = router;
