version: '3.7'
  ​
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'

  ​
mongo:
  image: mongo:latest
  ports:
    - "27017:27017"
  volumes:
    - mongodata:/data/db
  ​
redis:
  image: redis:alpine
  ports:
    - "6379:6379"
  volumes:
    - redisdata:/data

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
  volumes:
    - esdata:/usr/share/elasticsearch/data
  environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
  logging:
    driver: none
  ports:
    - 9300:9300
    - 9200:9200
  networks:
    - esnet
  ​
volumes:
  esdata:
  mysqldata:
  mongodata:
  redisdata:
networks:
  esnet: