module.exports = {
    USER_LOCATION_LANGUAGE_MAPPING : {'Uttar Pradesh' : ['hi'],
                            'West Bengal': ['bn'],
                            'Meghalaya': ['as', 'hi'],
                            'Nagaland': ['as', 'hi'],
                            'Chhattisgarh': ['hi'],
                            'Assam': ['as'],
                            'Karnataka': ['kn'],
                            'Himachal Pradesh': ['hi'],
                            'Punjab': ['pu'],
                            'Mizoram': ['as', 'hi'],
                            'Delhi': ['hi'],
                            'Bihar': ['hi'],
                            'Odisha': ['od'],
                            'Puducherry': ['ta'],
                            'Telangana': ['te'],
                            'Tripura': ['as', 'hi'],
                            'Andaman and Nicobar Islands': ['hi'],
                            'Maharashtra': ['mr'],
                            'Chandigarh': ['hi'],
                            'Rajasthan': ['hi'],
                            'Madhya Pradesh': ['hi'],
                            'Jharkhand': ['hi'],
                            'Gujarat': ['gu'],
                            'Manipur': ['as', 'hi'],
                            'Haryana': ['hi'],
                            'Jammu and Kashmir': ['hi'],
                            'Arunachal Pradesh': ['as', 'hi'],
                            'Andhra Pradesh': ['te'],
                            'Tamil Nadu': ['ta'],
                            'Uttarakhand': ['hi'],
                            'Kerala': ['ml']},
    USER_BOARD_LANGUAGE_MAPPING : {'CBSE': ['en'],
                            'UP Board': ['hi'],
                            'Bihar Board': ['hi'],
                            'Maharashtra Board': ['mr'],
                            'West Bengal Board': ['bn'],
                            'Madhya Pradesh Board': ['hi'],
                            'Rajasthan Board': ['hi'],
                            'Telangana Board': ['te'],
                            'Gujarat Board': ['gu'],
                            'ICSE': ['en'],
                            'Himachal Pradesh Board': ['hi'],
                            'Uttarakhand Board': ['hi'],
                            'Chhattisgarh Board': ['hi'],
                            'Jharkhand Board': ['hi'],
                            'Delhi Board': ['hi'],
                            'Punjab Board': ['pu'],
                            'Nepal Board': ['hi'],
                            'Karnataka Board': ['kn'],
                            'Odisha Board': ['od'],
                            'Andhra Pradesh Board': ['te'],
                            'Tamil Nadu Board': ['ta'],
                            'Haryana Board': ['hi'],
                            'Kerala Board': ['ml']},
    VIDEO_LANGUAGE_SET : ['en','hi','ta','bn','te','gu','kn','ml','mr','od','pu','as']
}

