module.exports = {
    stateAbbreviationMapping:
    {
        AP: 'ANDHRA PRADESH',
        AR: 'ARUNACHAL PRADESH',
        AS: 'ASSAM',
        BR: 'BIHAR',
        CG: 'CHHATTISGARH',
        GA: 'GOA',
        GJ: 'GUJARAT',
        HR: 'HARYANA',
        HP: 'HIMACHAL PRADESH',
        JK: 'JAMMU AND KASHMIR',
        JH: 'JHARKHAND',
        KA: 'KARNATAKA',
        KL: 'KERALA',
        MP: 'MADHYA PRADESH',
        MH: 'MAHARASHTRA',
        MN: 'MANIPUR',
        ML: 'MEGHALAYA',
        MZ: 'MIZORAM',
        NL: 'NAGALAND',
        OR: 'ODISHA',
        PB: 'PUNJAB',
        RJ: 'RAJASTHAN',
        SK: 'SIKKIM',
        TN: 'TAMIL NADU',
        TG: 'TELANGANA',
        TR: 'TRIPURA',
        UT: 'UTTARAKHAND',
        UP: 'UTTAR PRADESH',
        WB: 'WEST BENGAL',
        AN: 'ANDAMAN AND NICOBAR ISLANDS',
        CH: 'CHANDIGARH',
        DN: 'DADRA AND NAGAR HAVELI',
        DD: 'DAMAN AND DIU',
        DL: 'DELHI',
        LD: 'LAKSHADWEEP',
        PY: 'PONDICHERRY',
    },
    shirtSizes: [
        'S', 'M', 'L', 'XL', '2XL', '3XL',
    ],
};
