version: '3'

services:
    mysql:
        image: mariadb
        ports:
            - '3306:3306'
        volumes:
            - mysqldata:/var/lib/mysql
            - ./migration/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_PASSWORD: 'root'
            MYSQL_DATABASE: 'classzoo1'
        command: mysqld --sql_mode=""

    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongodata:/data/db

    redis:
        image: redis:alpine
        expose:
            - '6379'
        ports:
            - '6379:6379'
        volumes:
            - redisdata:/data

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        environment:
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
            - discovery.type=single-node
        ports:
            - '9300:9300'
            - '9200:9200'

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - '2181:2181'

    kafka:
        image: wurstmeister/kafka
        ports:
            - '29092:9092'
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_CREATE_TOPICS: 'vvs.notification:4:1,vvs.update:4:1,vvs.championship.coupon:4:1,push.notification:4:1'
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
    esdata:
    mysqldata:
    mongodata:
    redisdata:
